services:

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/frappe.cnf:ro

  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped

  redis-queue:
    image: redis:7-alpine
    restart: unless-stopped

  frappe:
    image: coworker/myfrappe:v15
    user: "${UID}:${GID}"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    working_dir: /frappe
    volumes:
      - ./frappe:/frappe
    ports:
      - "8000:8000"
      - "9000:9000"
    tty: true
    stdin_open: true
    command: bash